# Generated by Django 4.1.5 on 2023-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="status",
            field=models.CharField(
                choices=[("Доступно", "Доступно"), ("Не доступно", "Не доступно")],
                default="Доступно",
                max_length=100,
            ),
        ),
    ]
