# Generated by Django 4.1.5 on 2023-01-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydish',
            name='mage',
            field=models.ImageField(null=True, upload_to='category_dishes'),
        ),
    ]
