# Generated by Django 4.1.5 on 2023-02-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='status',
            field=models.CharField(default='Доступно', max_length=15),
        ),
        migrations.AlterField(
            model_name='dish',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
