# Generated by Django 4.1.5 on 2023-01-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categorydish_mage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydish',
            old_name='mage',
            new_name='image',
        ),
    ]
