# Generated by Django 4.1.5 on 2023-01-30 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_tableitem_waiter'),
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='menu',
        ),
        migrations.CreateModel(
            name='WaiterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
            ],
        ),
    ]
