# Generated by Django 4.1.5 on 2023-02-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("waiter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="waiter",
            name="tips",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="waiter.tips",
            ),
        ),
    ]
