# Generated by Django 4.1.5 on 2023-01-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_remove_waiter_menu_waiteritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiteritem',
            name='order',
        ),
        migrations.AddField(
            model_name='waiteritem',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiter.waiter'),
        ),
    ]
