# Generated by Django 4.1.5 on 2023-02-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_tips_waiter_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='tips',
        ),
        migrations.AddField(
            model_name='tips',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiter.waiter'),
        ),
    ]
