# Generated by Django 4.1.5 on 2023-02-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_waiter'),
        ('waiter', '0003_remove_waiteritem_order_waiteritem_waiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaiterItem',
        ),
    ]
