# Generated by Django 4.1.5 on 2023-02-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tips',
        ),
        migrations.DeleteModel(
            name='Tips',
        ),
    ]
