# Generated by Django 4.1.5 on 2023-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ManyToManyField(to='order.table'),
        ),
    ]
