# Generated by Django 4.1.5 on 2023-01-20 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
        ('order', '0004_remove_order_table_table_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
        migrations.RemoveField(
            model_name='table',
            name='places_amount',
        ),
        migrations.RemoveField(
            model_name='table',
            name='waiter',
        ),
        migrations.CreateModel(
            name='TableItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('places_amount', models.IntegerField(default=0, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.table')),
                ('waiter', models.ManyToManyField(to='waiter.waiter')),
            ],
        ),
    ]
