# Generated by Django 4.1.5 on 2023-01-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_table_is_reserved_remove_table_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitem',
            name='places_amount',
        ),
        migrations.AddField(
            model_name='table',
            name='places_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
