# Generated by Django 4.1.5 on 2023-02-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0005_remove_waiter_tips_tips_waiter'),
        ('order', '0005_remove_rating_order_order_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiter.tips'),
        ),
    ]
