# Generated by Django 4.1.5 on 2023-02-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_tips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Готовится", "Готовится"),
                    ("Блюда в зале", "Блюда в зале"),
                    ("Ожидает оплату", "Ожидает оплату"),
                    ("Оплачено", "Оплачено"),
                ],
                default="Зал 1",
                max_length=100,
            ),
        ),
    ]
