# Generated by Django 4.1.5 on 2023-01-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_tableitem_places_amount_table_places_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitem',
            name='order',
        ),
        migrations.AddField(
            model_name='tableitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='table',
            name='hall',
            field=models.CharField(choices=[('Зал 1', 'Зал 1'), ('Зал 2', 'Зал 2'), ('Зал 3', 'Зал 3'), ('Терраса', 'Терраса')], default='Зал 1', max_length=100),
        ),
    ]
