# Generated by Django 4.1.5 on 2023-01-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_tableitem_order_tableitem_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableitem',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='table_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.tableitem'),
        ),
    ]
