# Generated by Django 4.1.5 on 2023-01-20 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_tableitem_order_item_orderitem_table_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
