# Generated by Django 4.1.5 on 2023-01-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
    ]
