# Generated by Django 4.1.5 on 2023-02-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_order_customer_alter_order_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.rating"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
    ]
