# Generated by Django 4.1.5 on 2023-01-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Готовится', 'Готовиться'), ('Блюда в зале', 'Блюда в зале'), ('Ожидает оплату', 'Ожидает оплату')], default='Зал 1', max_length=100),
        ),
    ]
