# Generated by Django 4.1.5 on 2023-02-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_order_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="rating",
        ),
        migrations.AddField(
            model_name="rating",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
    ]
