# Generated by Django 4.1.5 on 2023-01-30 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0003_remove_waiteritem_order_waiteritem_waiter'),
        ('order', '0014_remove_tableitem_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiter.waiter'),
        ),
    ]
