# Generated by Django 4.1.5 on 2023-02-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0003_remove_waiteritem_order_waiteritem_waiter'),
        ('order', '0017_alter_order_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waiter.waiter'),
        ),
    ]
