# Generated by Django 4.1.5 on 2023-02-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='table_item',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.table'),
        ),
        migrations.DeleteModel(
            name='TableItem',
        ),
    ]
