# Generated by Django 4.1.5 on 2023-02-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_orderitem_table_item_order_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tips',
        ),
        migrations.AddField(
            model_name='order',
            name='tips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.tips'),
        ),
    ]
